### ISSUE TITLE
What to do with author/contributor fields in package.json?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/node-schedule#1]
@rarkins What do you want to do with the `author` and `contributor` fields in our `package.json`?

Option 1: Add myself as contributor, keep original author
Option 2: Move author to contributor, add HonkingGoose as author

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#people-fields-author-contributors

**Comment by HonkingGoose** [comment]
@rarkins did you close my project board maybe?

**Comment by rarkins** [comment]
I didn't delete anything or ever see them. When I go into settings just now:

![image](https://user-images.githubusercontent.com/6311784/122247014-55e7cb00-cec7-11eb-8876-6e842792f3ed.png)

I enabled it now and I see one issue came back:

![image](https://user-images.githubusercontent.com/6311784/122247088-64ce7d80-cec7-11eb-8c92-3947ffa485a8.png)

**Comment by rarkins** [comment]
I think put yourself as author and move the original author to contributor.

**Comment by HonkingGoose** [comment]
> 
> 
> I didn't delete anything or ever see them. When I go into settings just now:
> 
> ![image](https://user-images.githubusercontent.com/6311784/122247014-55e7cb00-cec7-11eb-8876-6e842792f3ed.png)
> 
> I enabled it now and I see one issue came back:
> 
> ![image](https://user-images.githubusercontent.com/6311784/122247088-64ce7d80-cec7-11eb-8c92-3947ffa485a8.png)

Whew, at least it came back! 😄 

Maybe I mis-clicked something...
