### ISSUE TITLE
Setup branch protection rules for main branch

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/node-schedule#11]
**What would you like node-schedule to be able to do?**

We should protect the `main` branch properly by requiring the current tests to pass before you can squash-merge/rebase merge a PR.

I think it's also a good time to prevent force pushes to the `main` branch, as I'm ready to accept contributions from the Renovate team on things I'm not qualified to change. 😄 

**Did you already have any implementation ideas?**

I'd say just copy/paste what we have from `renovatebot/renovate` into here so that we keep the conventions/behavior the same between repositories in the org. 😄

I don't have enough rights to setup the branch protection rules, so somebody else will need to set that up. 😉 😉

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/122350210-5165f580-cf4d-11eb-9411-5c16b8bd60c9.png)

**Comment by HonkingGoose** [comment]
@rarkins, I like the overall setup, nearly good to go:

GitHub changed the way you specify the "required tests" recently, you need to write a part of the test name before you can select it under "Require status checks to pass before merging". I don't see Jest or Lint status checks in the list of required tests right now.

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/122352086-15cc2b00-cf4f-11eb-8c61-0ec47d9a838b.png)

I couldn't find any without 14.x

**Comment by HonkingGoose** [comment]
That's OK, you see the `14.x` in the name because I use a test matrix like this:

https://github.com/renovatebot/node-schedule/blob/eccdccdaf7f6532cc9b17dd4d84d1d92a2b2371a/.github/workflows/jest.yml#L13-L15

I think it's possible to change the name by dropping the matrix. But I'd need to read the GitHub docs on Action syntax a bit more to be sure... 😄 I really only use the basic boilerplate setups. 😄
