### ISSUE TITLE
Publishing with `semantic-release`

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/node-schedule#3]
**What would you like node-schedule to be able to do?**

Once the repository/package is in a good state, we can start thinking about publishing.

**Did you already have any implementation ideas?**

- Install `semantic-release` with yarn into `package.json`
- Configure `semantic-release` properly
- Ensure that `semantic-release` only creates a release if all pre-requisites are met

**Comment by HonkingGoose** [comment]
I'm labeling this `status:blocked` because the repo is not yet stable/pretty enough to consider publishing. 😄

**Comment by HonkingGoose** [comment]
Quote from @viceice:

> yes, the package is now compatible to be used in esm javascript module sytem, which is the new standard way or javascript for node js.
> 
> A lot packages are starting to be esm only, but renovate is not ready yet, so we publish in both types.
> 
> When renovate is ready for esm only, we can drop the commonjs version

So the goal is to publish 2 packages, one for ESM and one for CommonJS.

End-goal is to only publish ESM module (probably major version bump then!)

**Comment by viceice** [comment]
if you checkout the e2e tests, you can see we don't need to change anything in semantic-release. I've prepared everything for packaging required files.

so we just need to enable semantic release.

**Comment by viceice** [comment]
No, th goal is to publish one package for commonjs and esm. which i've already done, just run:

```shell
yarn install
yarn build
yarn pack
``` 

then you get the packaged tgz file to test with

**Comment by HonkingGoose** [comment]
@viceice Do you know a lot about `semantic-release`? I've read their docs, and it's really complicated. I think letting me set things up will only lead to frustration on your end, as you probably need to fix everything I do... 😄 

So I think I'll let somebody else from the core renovate team set up publishing for us.
