### ISSUE TITLE
Turn on Renovate bot on repository

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/node-schedule#4]
**What would you like node-schedule to be able to do?**

I've copy/pasted the Renovate bot config from the main Renovate bot repository and made some adjustments.
We're nearly ready to get the bot running, once we have some basic GitHub Action workflows running (PR #2).

**Did you already have any implementation ideas?**

- [ ] Ensure we have some basic GitHub actions to test if the proposed update works/breaks
- [ ] Review `renovate.json` file (Don't need/want automerge for now.)
- [ ] Make adjustments if needed to `renovate.json` file

**Comment by HonkingGoose** [comment]
I'm considering this blocked until we have some GitHub Action workflows. 😄

**Comment by rarkins** [comment]
Done
