### ISSUE TITLE
Move what we need into Renovate itself and archive this repository

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/node-schedule#43]
### Original reason for the project

I think the big idea was that we "package up" the `node-schedule` repository and use it as a dependency in our `renovate` repository. This package would also be the source of truth for the node schedule data file that currently lives in the main `renovatebot/renovate` repository.

I and some others worked to get the `node-schedule` repository nearly ready to use.

### What changed between project start and now

@JamieMagee made a nice GitHub Action for us, that updates these static data files:

- https://github.com/renovatebot/renovate/pull/17080

We never got around to publishing a package, and using that package as a dependency for the Renovate bot project. _Maybe_ that's an indicator that we don't _really_ need the things in this repository?

### Work to do on this project, if we keep it

We're not publishing any packages on this project. I meant for us to start using the semver release tooling, that we're already using on the main Renovate project:

- #3

### Summary

Do we want to keep (parts) of this project, or drop or archive it?

**Comment by viceice** [comment]
i think we should drop this

**Comment by rarkins** [comment]
@JamieMagee do you agree?

**Comment by JamieMagee** [comment]
I don't think I have the full context on this repo, but from what I can find it is a nicer packaged version of this?

https://github.com/renovatebot/renovate/blob/8bd77f747b3da59cc955b2fc4ba3301bcb680ea2/lib/modules/versioning/node/index.ts#L51-L60

I think we should move what we need into Renovate itself and archive this repository.

**Comment by viceice** [comment]
i don't see much value here beside the eol function. we only need  new script to download the schedule[^1]

[^1]: https://raw.githubusercontent.com/nodejs/LTS/master/schedule.json
