### ISSUE TITLE
Convert schedule.json to TypeScript

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/node-schedule#5]
**What would you like node-schedule to be able to do?**

@viceice wanted to convert the `schedule.json` to TypeScript, so that the Renovate bot maintainers can use a simple import without `async / await`.

**Did you already have any implementation ideas?**

We'll first need to make the package use TypeScript instead of JavaScript. That will probably make doing things like converting JSON to TypeScript easier and safer.

**Comment by HonkingGoose** [comment]
Labeling this `status:blocked`, I think we need #6 before we can start.

**Comment by viceice** [comment]
This is now compiled to javascript 😄  So i think we can clse this.

**Comment by HonkingGoose** [comment]
Oh thank you! 😄 

Let's close this then, if you think we're done. 😄
