### ISSUE TITLE
Use TypeScript instead of JavaScript for code/tests

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/node-schedule#6]
**What would you like node-schedule to be able to do?**

It's probably a good idea to use TypeScript instead of JavaScript, so that we're consistent with our programming language between this repository and the main Renovate repository.

As an added bonus we'll probably have a safer programming language to work in, so that we can catch stupid stuff earlier. 😄 

**Did you already have any implementation ideas?**

I've taken a look at the migration guide from JavaScript to TypeScript in the official Typescript docs, it shouldn't be that hard for a programmer familiar with TypeScript to migrate this repository and tooling.

I'm not that good with TypeScript (or JavaScript for that matter 🙈 ) to be able to migrate us. So I'd like somebody else to do this, or maybe we could do it together, so that I can learn a bit (but that'll slow you down...).

[TypeScript docs on migrating from JavaScript](https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html)

**Comment by patlehmann1** [comment]
I'm not familiar with the codebase, but I'm open to help wherever I can.

**Comment by HonkingGoose** [comment]
@patlehmann1 Thank you for wanting to help! 😄 👍 

There's really only 2 files with relevant code, the `index.js` file in `/src` and the `test.js` file in `/test`.

The basic idea is that we load in the `schedule.json` file in the root of the repo, and use that in `index.js` with some functions.

The tests are written in Jest they should be do-able to migrate to TypeScript as well.

A basic JavaScript to TypeScript conversion following the official TypeScript docs is enough for now. We can make it prettier/better once we actually get things working under TypeScript. 😉

---

@rarkins do you have any requirements?

**Comment by HonkingGoose** [comment]
@viceice What do you think?

**Comment by viceice** [comment]
sure, good idea. But i'm out of time to do the convert. sorry.

**Comment by HonkingGoose** [comment]
I've just checked the code and tests, and I'm not completely happy with either.
So before you start I'd like to try to clean it up a bit... 😄 

Put input validation into own function `inputValidation` to sanitize the input:

- [ ] Throw error on for bad input (non-sensical strings!)
- [ ] Reject input that exceeds reasonable bounds (version character limit set to something reasonable)
- [ ] Clearer error messages

Tests:

- [ ] Also the tests are testing too much at once, so I'd like to make it so that tests only test one specific thing at a time.
- [ ] Add tests for input validation, test each Error reason seperately

**Comment by HonkingGoose** [comment]
Hi @patlehmann1, I've done the cleanup/refactoring that I can do right now, and I've added a simple Jest test configuration.

You're good to migrate the code from JavaScript to TypeScript now. 😉

**Comment by patlehmann1** [comment]
@HonkingGoose it will probably take me a while to get familiar with the codebase here, but I'll see what I can do.
